layout_spectrum: 0.1007008
typography_spectrum: 0.9381461
color:
  saturation: 0.397215
  lightness: 0.1892802
  brandStrength: 0.2587464
  rhythmicContrast: 0.1193388
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: playmobil
